# -*- coding: utf-8 -*-
"""Grupo6_Projeto_Final_PSD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EVCwuDHkJbSn6Jz57bXXzmps2_gHRa6o

# **Projeto de Processamento de Sinais Digitais (Grupo 6)**
### Projeto 2: Análise de Sinais de ECG via Filtragem FIR, Convolução Rápida, Filtros de Gabor 1D e Espectro de Potência Tempo-Frequência

> Pedro Arthur, RA: 814248

> Juliano Eleno Silva Pádua, RA: 800812

> Matheo, RA: 821293

# 0. Resumo do projeto

Montamos um pipeline de Processamento Digital de Sinais aplicado a batimentos ECG da MIT-BIH Arrhythmia Database. O fluxo parte da inspeção do sinal bruto, aplica a filtragem FIR, justificada a partir de evidências visuais e espectrais, verifica a equivalência entre convolução temporal e convolução por FFT, analisa filtros de Gabor 1D e extrai features para comparar uma SVM supervisionada com uma One-Class SVM.

A unidade de análise final é o batimento segmentado em torno da anotação da base. O rótulo binário é usado apenas na avaliação, com `N` como normal e os demais símbolos válidos de batimento como anomalia. A One-Class SVM é treinada somente com batimentos normais, enquanto a SVM supervisionada entra como baseline didático.

# 1. Pré-configuração

Aqui, reunimos as dependências, as pastas usadas no ambiente Colab, os arquivos auxiliares e as funções do notebook. Colocamos no começo para que as próximas seções fiquem focadas na análise do sinal, sem misturar implementação de apoio com interpretação dos resultados.

## 1.1 Instalação das dependências

As bibliotecas externas usadas no trabalho são instaladas no início para que o notebook rode em um runtime limpo do Colab. A biblioteca `wfdb` acessa os registros e anotações da MIT-BIH. `scipy`, `numpy` e `pandas` sustentam o processamento numérico. `matplotlib` e `seaborn` são usados para visualização. `scikit-learn` fornece as SVMs e as métricas de avaliação.
"""

!pip -q install wfdb scikit-learn scipy pandas matplotlib seaborn

"""## 1.2 Importação de bibliotecas

Todas as importações ficam concentradas nesta célula para deixar claro o conjunto de ferramentas usado no projeto.
"""

from __future__ import annotations

from pathlib import Path
import os
from time import perf_counter
import urllib.request
import warnings

import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import numpy as np
import pandas as pd
import seaborn as sns
from scipy import signal
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    confusion_matrix,
    f1_score,
    precision_recall_curve,
    precision_score,
    recall_score,
    roc_auc_score,
    roc_curve,
)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import OneClassSVM, SVC
import wfdb

warnings.filterwarnings("ignore", category=RuntimeWarning)
sns.set_theme(style="whitegrid", context="notebook")

RANDOM_STATE = 42
rng = np.random.default_rng(RANDOM_STATE)

"""## 1.3 Pastas do runtime

Os dados brutos, as imagens de apoio, as figuras geradas e as tabelas de resultados ficam separados em pastas dentro de `/content`. Essa organização ajuda a encontrar rapidamente os artefatos produzidos durante a execução.
"""

BASE_DIR = Path("/content")
RAW_DATA_DIR = BASE_DIR / "raw_data"
DATA_DIR = RAW_DATA_DIR / "mitdb"
IMG_DIR = BASE_DIR / "imgs"
FIG_DIR = BASE_DIR / "figuras_ecg"
RESULTS_DIR = BASE_DIR / "resultados_ecg"

for folder in (RAW_DATA_DIR, DATA_DIR, IMG_DIR, FIG_DIR, RESULTS_DIR):
    folder.mkdir(parents=True, exist_ok=True)

ECG_IMAGE_URL = "https://ecgwaves.com/wp-content/uploads/2018/01/ekg-ecg-interpretation-p-qrs-st-t-wave.jpg"
ECG_IMAGE_PATH = IMG_DIR / "ekg_ecg_interpretation_p_qrs_st_t_wave.jpg"

print("Pasta de dados:", DATA_DIR)
print("Pasta de imagens:", IMG_DIR)
print("Pasta de figuras:", FIG_DIR)
print("Pasta de resultados:", RESULTS_DIR)

"""## 1.4 Download da base e da imagem de apoio

A MIT-BIH é baixada diretamente do PhysioNet para tornar o notebook reprodutível no Colab. A imagem anatômica do ECG é salva em `/content/imgs` para ser usada depois em uma célula Markdown da explicação fisiológica.
"""

def download_support_image(image_url=ECG_IMAGE_URL, destination_path=ECG_IMAGE_PATH):
    destination_path = Path(destination_path)
    destination_path.parent.mkdir(parents=True, exist_ok=True)
    if not destination_path.exists():
        urllib.request.urlretrieve(image_url, destination_path)
        print(f"Imagem baixada em {destination_path}")
    else:
        print(f"Imagem ja encontrada em {destination_path}")
    return destination_path


if not (DATA_DIR / "RECORDS").exists():
    wfdb.dl_database("mitdb", dl_dir=DATA_DIR.as_posix())
else:
    print("MIT-BIH ja encontrada em", DATA_DIR)

download_support_image()

"""## 1.5 Constantes do protocolo

Os símbolos válidos representam batimentos avaliáveis da MIT-BIH. O rótulo binário usa `N` como normal e os demais símbolos válidos como anomalia. Os registros paced-heavy ficam fora da versão principal para evitar que a tarefa vire predominantemente detecção de marcapasso.
"""

VALID_BEAT_SYMBOLS = {
    "N", "L", "R", "B", "A", "a", "J", "S", "V", "r", "F", "e", "j", "n", "E", "Q"
}
NORMAL_SYMBOL = "N"
PACED_HEAVY_RECORDS = {"102", "104", "107", "217"}

DS1_RECORDS = (
    "101", "106", "108", "109", "112", "114", "115", "116", "118", "119", "122",
    "124", "201", "203", "205", "207", "208", "209", "215", "220", "223", "230",
)
DS2_RECORDS = (
    "100", "103", "105", "111", "113", "117", "121", "123", "200", "202", "210",
    "212", "213", "214", "219", "221", "222", "228", "231", "232", "233", "234",
)

TRAIN_RECORDS = tuple(r for r in DS1_RECORDS if r not in PACED_HEAVY_RECORDS)
TEST_RECORDS = tuple(r for r in DS2_RECORDS if r not in PACED_HEAVY_RECORDS)
ALL_PROTOCOL_RECORDS = TRAIN_RECORDS + TEST_RECORDS

"""## 1.6 Funções de apoio

As próximas células concentram as funções usadas ao longo do notebook. Na apresentação, vale explicar as funções mais importantes, especialmente a convolução temporal manual, a convolução por FFT, o projeto dos filtros FIR e os filtros de Gabor. Depois dessa explicação, a seção pode ser recolhida para facilitar a navegação.

### 1.6.1 Leitura dos registros e seleção de janelas

Estas funções carregam o sinal, selecionam o canal MLII quando disponível, filtram os símbolos de batimento válidos e recortam janelas de análise.
"""

def select_mlii_channel(record):
    names = list(record.sig_name or [])
    upper = [str(name).upper() for name in names]
    if "MLII" in upper:
        idx = upper.index("MLII")
        return idx, names[idx]
    return 0, names[0] if names else "canal_0"


def load_record(record_name, data_dir=DATA_DIR):
    rec = wfdb.rdrecord((data_dir / record_name).as_posix())
    ann = wfdb.rdann((data_dir / record_name).as_posix(), "atr")
    channel_idx, channel_name = select_mlii_channel(rec)
    x = np.asarray(rec.p_signal[:, channel_idx], dtype=float)
    fs = float(rec.fs)
    ann_samples = np.asarray(ann.sample, dtype=int)
    ann_symbols = np.asarray(ann.symbol, dtype=str)
    return x, fs, channel_name, ann_samples, ann_symbols


def valid_beat_mask(symbols):
    return np.array([symbol in VALID_BEAT_SYMBOLS for symbol in symbols], dtype=bool)


def binary_label(symbol):
    if symbol == NORMAL_SYMBOL:
        return 0
    if symbol in VALID_BEAT_SYMBOLS:
        return 1
    raise ValueError(f"Simbolo invalido para avaliacao: {symbol}")


def make_sample_window_from_beats(beat_samples, fs, start_beat_idx=1, n_beats=4, margin_s=0.25):
    chosen = beat_samples[start_beat_idx:start_beat_idx + n_beats]
    margin = int(round(margin_s * fs))
    start = max(0, int(chosen[0]) - margin)
    end = int(chosen[-1]) + margin
    return start, end, chosen


def full_beat_bounds(center_sample, fs, n_samples, pre_s=0.25, post_s=0.45):
    pre = int(round(pre_s * fs))
    post = int(round(post_s * fs))
    start = int(center_sample) - pre
    end = int(center_sample) + post
    if start < 0 or end > n_samples:
        return None
    return start, end


def rr_context(valid_samples, idx, fs):
    rr_prev = np.nan
    rr_next = np.nan
    if idx > 0:
        rr_prev = (valid_samples[idx] - valid_samples[idx - 1]) / fs
    if idx + 1 < len(valid_samples):
        rr_next = (valid_samples[idx + 1] - valid_samples[idx]) / fs
    return float(rr_prev), float(rr_next)

"""### 1.6.2 Visualização

Estas funções padronizam os gráficos do sinal no tempo, da PSD e dos filtros. Elas não alteram os dados, apenas tornam a leitura visual consistente.
"""

def plot_ecg_window(t, x, ann_samples_local=None, ann_symbols_local=None, title="ECG"):
    fig, ax = plt.subplots(figsize=(13, 4))
    ax.plot(t, x, color="#1f77b4", linewidth=1.1)
    ax.set_title(title)
    ax.set_xlabel("Tempo (s)")
    ax.set_ylabel("Amplitude (mV)")
    if ann_samples_local is not None:
        for sample, symbol in zip(ann_samples_local, ann_symbols_local, strict=False):
            if 0 <= sample < len(x):
                ax.axvline(t[sample], color="#d62728", alpha=0.5, linewidth=0.9)
                ax.text(t[sample], np.max(x), symbol, color="#d62728", ha="center", va="bottom")
    fig.tight_layout()
    return fig, ax


def plot_psd(x, fs, title, max_freq=100.0):
    freqs, pxx = signal.welch(x, fs=fs, nperseg=min(len(x), 2048))
    fig, ax = plt.subplots(figsize=(12, 4))
    ax.semilogy(freqs, pxx, color="#1f77b4", linewidth=1.1)
    ax.axvspan(0.0, 0.5, color="#ffbf69", alpha=0.25, label="deriva")
    ax.axvspan(59.0, 61.0, color="#ef476f", alpha=0.22, label="rede")
    ax.axvspan(40.0, max_freq, color="#6c757d", alpha=0.14, label="alta frequencia")
    ax.set_xlim(0, max_freq)
    ax.set_title(title)
    ax.set_xlabel("Frequencia (Hz)")
    ax.set_ylabel("PSD")
    ax.legend(loc="upper right")
    fig.tight_layout()
    return fig, ax


def beat_zoom_xlim(t, ann_local, fs, n_beats=2, pad_before_s=0.12, pad_after_s=0.45):
    if len(ann_local) == 0:
        return float(t[0]), float(t[-1])
    last_idx = min(len(ann_local) - 1, max(0, n_beats - 1))
    start = max(float(t[0]), float(ann_local[0] / fs - pad_before_s))
    end = min(float(t[-1]), float(ann_local[last_idx] / fs + pad_after_s))
    return start, end

"""### 1.6.3 Métricas espectrais e análise de bandas

Estas funções calculam potência por banda, tabela de PSD, SNR aproximada e descritores compactos do espectro.
"""

def band_power(x, fs, low_hz, high_hz, nperseg=None):
    nperseg = nperseg or min(len(x), 2048)
    freqs, pxx = signal.welch(x, fs=fs, nperseg=nperseg)
    mask = (freqs >= low_hz) & (freqs <= high_hz)
    if not np.any(mask):
        return 0.0
    return float(np.trapezoid(pxx[mask], freqs[mask]))


def psd_table(x, fs):
    bands = {
        "deriva_0_0p5": (0.0, 0.5),
        "baixa_0p5_4": (0.5, 4.0),
        "p_qrs_4_8": (4.0, 8.0),
        "qrs_8_20": (8.0, 20.0),
        "alta_20_40": (20.0, 40.0),
        "muscular_40_100": (40.0, 100.0),
        "rede_59_61": (59.0, 61.0),
    }
    rows = []
    total = band_power(x, fs, 0.0, min(100.0, fs / 2.0))
    for name, (lo, hi) in bands.items():
        p = band_power(x, fs, lo, min(hi, fs / 2.0))
        rows.append({
            "banda": name,
            "faixa_hz": f"{lo:g}-{hi:g}",
            "potencia": p,
            "percentual_0_100": 100.0 * p / max(total, 1e-20),
        })
    return pd.DataFrame(rows)


def snr_band_estimate_db(x, fs, signal_band=(0.5, 40.0), noise_bands=((0.0, 0.5), (40.0, 100.0), (59.0, 61.0))):
    p_signal = band_power(x, fs, signal_band[0], signal_band[1])
    p_noise = 0.0
    for lo, hi in noise_bands:
        p_noise += band_power(x, fs, lo, min(hi, fs / 2.0))
    return 10.0 * np.log10(max(p_signal, 1e-20) / max(p_noise, 1e-20))


def snr_residual_estimate_db(filtered, residual):
    p_signal = float(np.mean(np.asarray(filtered) ** 2))
    p_noise = float(np.mean(np.asarray(residual) ** 2))
    return 10.0 * np.log10(max(p_signal, 1e-20) / max(p_noise, 1e-20))

"""### 1.6.4 Projeto e aplicação dos filtros FIR

Estas funções implementam a cadeia FIR. A ordem da janela de Hamming é estimada por `N = 3,3 fs / delta_f`, o que deixa explícita a relação entre largura de transição e número de coeficientes.

Antes da cascata, removemos a média do sinal com `x - mean(x)`. Essa etapa elimina o componente DC, isto é, um deslocamento vertical constante que não representa uma oscilação fisiológica do ECG. Ela não substitui o passa-alta em 0,5 Hz, porque o passa-alta também reduz variações lentas ao longo do tempo. A remoção de média apenas centraliza o registro em torno de zero para que os filtros seguintes trabalhem sem um offset constante.
"""

def hamming_numtaps(fs, transition_hz):
    n = int(np.ceil(3.3 * fs / transition_hz))
    return n + 1 if n % 2 == 0 else n


def design_highpass_hamming(fs, cutoff_hz=0.5, transition_hz=0.5):
    n = hamming_numtaps(fs, transition_hz)
    return signal.firwin(n, cutoff_hz, fs=fs, window="hamming", pass_zero=False)


def design_lowpass_hamming(fs, cutoff_hz=40.0, transition_hz=8.0):
    n = hamming_numtaps(fs, transition_hz)
    return signal.firwin(n, cutoff_hz, fs=fs, window="hamming", pass_zero=True)


def remez_numtaps(fs, transition_hz):
    n = int(np.clip(round(fs / transition_hz), 101, 801))
    return n + 1 if n % 2 == 0 else n


def design_highpass_remez(fs, cutoff_hz=0.5, transition_hz=0.5, numtaps=None):
    if numtaps is None:
        numtaps = remez_numtaps(fs, transition_hz)
    edge_stop = max(0.05, cutoff_hz - transition_hz / 2.0)
    edge_pass = cutoff_hz + transition_hz / 2.0
    return signal.remez(
        numtaps,
        [0.0, edge_stop, edge_pass, fs / 2.0],
        [0.0, 1.0],
        fs=fs,
        maxiter=50,
        grid_density=32,
    )


def design_lowpass_remez(fs, cutoff_hz=40.0, transition_hz=8.0, numtaps=None):
    if numtaps is None:
        numtaps = remez_numtaps(fs, transition_hz)
    edge_pass = max(0.05, cutoff_hz - transition_hz / 2.0)
    edge_stop = cutoff_hz + transition_hz / 2.0
    return signal.remez(
        numtaps,
        [0.0, edge_pass, edge_stop, fs / 2.0],
        [1.0, 0.0],
        fs=fs,
        maxiter=50,
        grid_density=32,
    )


def make_hamming_filters(fs):
    return {
        "passa_alta_0p5": design_highpass_hamming(fs, cutoff_hz=0.5, transition_hz=0.5),
        "passa_baixa_40": design_lowpass_hamming(fs, cutoff_hz=40.0, transition_hz=8.0),
    }


def make_remez_filters(fs):
    return {
        "passa_alta_0p5": design_highpass_remez(fs, cutoff_hz=0.5, transition_hz=0.5),
        "passa_baixa_40": design_lowpass_remez(fs, cutoff_hz=40.0, transition_hz=8.0),
    }


def make_butter_iir_filters(fs, order=4):
    return {
        "passa_alta_0p5": signal.butter(order, 0.5, btype="highpass", fs=fs, output="sos"),
        "passa_baixa_40": signal.butter(order, 40.0, btype="lowpass", fs=fs, output="sos"),
    }


def apply_filtfilt_fir(x, h):
    return signal.filtfilt(h, [1.0], x)


def apply_filter_stages(x, filters):
    y0 = np.asarray(x, dtype=float) - np.mean(x)
    stages = {"remocao_media": y0}
    y = y0.copy()
    for name, h in filters.items():
        y = apply_filtfilt_fir(y, h)
        stages[name] = y
    return stages


def apply_iir_stages(x, filters):
    y0 = np.asarray(x, dtype=float) - np.mean(x)
    stages = {"remocao_media": y0}
    y = y0.copy()
    for name, sos in filters.items():
        y = signal.sosfiltfilt(sos, y)
        stages[name] = y
    return stages


def plot_filter_response(filters, fs, title="Resposta em frequencia dos filtros FIR"):
    fig, ax = plt.subplots(figsize=(12, 4))
    for name, h in filters.items():
        w, H = signal.freqz(h, worN=4096, fs=fs)
        ax.plot(w, 20 * np.log10(np.maximum(np.abs(H), 1e-8)), label=f"{name} ({len(h)} coef.)")
    ax.set_xlim(0, 100)
    ax.set_ylim(-90, 5)
    ax.set_title(title)
    ax.set_xlabel("Frequencia (Hz)")
    ax.set_ylabel("Magnitude (dB)")
    ax.legend(loc="lower left")
    fig.tight_layout()
    return fig, ax


def plot_iir_response(filters, fs, title="Resposta em frequencia dos filtros IIR"):
    fig, ax = plt.subplots(figsize=(12, 4))
    for name, sos in filters.items():
        w, H = signal.sosfreqz(sos, worN=4096, fs=fs)
        ax.plot(w, 20 * np.log10(np.maximum(np.abs(H), 1e-8)), label=f"{name} ({sos.shape[0]} SOS)")
    ax.set_xlim(0, 100)
    ax.set_ylim(-90, 5)
    ax.set_title(title)
    ax.set_xlabel("Frequencia (Hz)")
    ax.set_ylabel("Magnitude (dB)")
    ax.legend(loc="lower left")
    fig.tight_layout()
    return fig, ax


def time_stage_application(label, apply_fn):
    start = perf_counter()
    stages = apply_fn()
    elapsed_ms = (perf_counter() - start) * 1000.0
    return stages, {"metodo": label, "tempo_ms": elapsed_ms}


def plot_filter_response_comparison(filter_sets, fs):
    fig, ax = plt.subplots(figsize=(12, 4))
    for method_name, filters in filter_sets.items():
        for filter_name, h in filters.items():
            w, H = signal.freqz(h, worN=4096, fs=fs)
            label = f"{method_name} - {filter_name} ({len(h)} coef.)"
            ax.plot(w, 20 * np.log10(np.maximum(np.abs(H), 1e-8)), linewidth=1.0, label=label)
    ax.set_xlim(0, 100)
    ax.set_ylim(-90, 5)
    ax.set_title("Comparacao das respostas em frequencia dos filtros FIR")
    ax.set_xlabel("Frequencia (Hz)")
    ax.set_ylabel("Magnitude (dB)")
    ax.legend(loc="center left", bbox_to_anchor=(1.01, 0.5))
    fig.tight_layout(rect=[0, 0, 0.78, 1])
    return fig, ax

"""### 1.6.5 Convolução no tempo e por FFT

A função `linear_convolution_full_manual` é uma das funções centrais do trabalho, porque implementa o somatório da convolução sem chamar uma função pronta de convolução. A versão por FFT usa zero-padding para reproduzir a convolução linear.
"""

def linear_convolution_full_manual(x, h):
    x = np.asarray(x, dtype=float)
    h = np.asarray(h, dtype=float)
    y = np.zeros(len(x) + len(h) - 1, dtype=float)
    for n in range(len(y)):
        soma = 0.0
        k_min = max(0, n - (len(h) - 1))
        k_max = min(len(x) - 1, n)
        for k in range(k_min, k_max + 1):
            soma += x[k] * h[n - k]
        y[n] = soma
    return y


def same_from_full_convolution(y_full, len_x, len_h):
    start = (len_h - 1) // 2
    end = start + len_x
    return y_full[start:end]


def linear_convolution_same_manual(x, h):
    y_full = linear_convolution_full_manual(x, h)
    return same_from_full_convolution(y_full, len(x), len(h))


def fft_convolution_same_linear(x, h):
    x = np.asarray(x, dtype=float)
    h = np.asarray(h, dtype=float)
    n_linear = len(x) + len(h) - 1
    X = np.fft.rfft(x, n=n_linear)
    H = np.fft.rfft(h, n=n_linear)
    y_full = np.fft.irfft(X * H, n=n_linear)
    return same_from_full_convolution(y_full, len(x), len(h))


def fft_convolution_circular_wrong(x, h):
    x = np.asarray(x, dtype=float)
    h = np.asarray(h, dtype=float)
    X = np.fft.rfft(x, n=len(x))
    H = np.fft.rfft(h, n=len(x))
    return np.fft.irfft(X * H, n=len(x))


def mse(a, b):
    a = np.asarray(a, dtype=float)
    b = np.asarray(b, dtype=float)
    return float(np.mean((a - b) ** 2))

"""### 1.6.6 Métricas de preservação do pico R

Estas funções medem se a filtragem preservou a estrutura temporal mais importante para a segmentação dos batimentos.
"""

def r_peak_error_table(raw, filtered, ann_local, fs, search_ms=50.0):
    half = int(round(search_ms * 1e-3 * fs))
    rows = []
    for sample in ann_local:
        lo = max(0, int(sample) - half)
        hi = min(len(raw), int(sample) + half + 1)
        if hi <= lo:
            continue
        raw_seg = raw[lo:hi]
        filt_seg = filtered[lo:hi]
        raw_idx = lo + int(np.argmax(np.abs(raw_seg - np.mean(raw_seg))))
        filt_idx = lo + int(np.argmax(np.abs(filt_seg - np.mean(filt_seg))))
        raw_amp = float(raw[raw_idx])
        filt_amp = float(filtered[filt_idx])
        err = 100.0 * abs(filt_amp - raw_amp) / max(abs(raw_amp), 1e-20)
        rows.append({
            "amostra_anotada": int(sample),
            "pico_bruto": raw_idx,
            "pico_filtrado": filt_idx,
            "deslocamento_ms": (filt_idx - raw_idx) / fs * 1000.0,
            "amp_bruta": raw_amp,
            "amp_filtrada": filt_amp,
            "erro_R_percentual": err,
        })
    return pd.DataFrame(rows)


def denoising_summary(raw, filtered, fs):
    residual = raw - filtered
    rows = []
    for name, lo, hi in [
        ("deriva_0_0p5", 0.0, 0.5),
        ("rede_59_61", 59.0, 61.0),
        ("alta_40_100", 40.0, 100.0),
        ("passante_0p5_40", 0.5, 40.0),
    ]:
        p_raw = band_power(raw, fs, lo, min(hi, fs / 2.0))
        p_filt = band_power(filtered, fs, lo, min(hi, fs / 2.0))
        rows.append({
            "banda": name,
            "potencia_bruta": p_raw,
            "potencia_filtrada": p_filt,
            "mudanca_db": 10.0 * np.log10(max(p_filt, 1e-20) / max(p_raw, 1e-20)),
        })
    band_rows = pd.DataFrame(rows)
    snr_rows = pd.DataFrame([
        {"metrica": "SNR por bandas no bruto", "valor_db": snr_band_estimate_db(raw, fs)},
        {"metrica": "SNR por bandas no filtrado", "valor_db": snr_band_estimate_db(filtered, fs)},
        {"metrica": "SNR filtrado/residuo", "valor_db": snr_residual_estimate_db(filtered, residual)},
    ])
    return band_rows, snr_rows

"""### 1.6.7 Filtros de Gabor 1D

Estas funções constroem os kernels de Gabor e calculam respostas locais. A parte par e a parte ímpar permitem formar uma energia local menos dependente da fase.
"""

def gabor_kernel(fs, f0_hz, sigma_s, phase=0.0, n_sigma=4.0):
    half = int(np.ceil(n_sigma * sigma_s * fs))
    t = np.arange(-half, half + 1) / fs
    envelope = np.exp(-(t ** 2) / (2.0 * sigma_s ** 2))
    h = envelope * np.cos(2.0 * np.pi * f0_hz * t + phase)
    h = h - np.mean(h)
    norm = np.sqrt(np.sum(h ** 2))
    if norm > 0:
        h = h / norm
    return t, h


def gabor_response_component(x, fs, f0_hz, sigma_s, component="even"):
    phase = 0.0 if component == "even" else np.pi / 2.0
    _, h = gabor_kernel(fs, f0_hz, sigma_s, phase=phase)
    return signal.fftconvolve(x, h, mode="same")


def gabor_energy_response(x, fs, f0_hz, sigma_s):
    even = gabor_response_component(x, fs, f0_hz, sigma_s, "even")
    odd = gabor_response_component(x, fs, f0_hz, sigma_s, "odd")
    return even ** 2 + odd ** 2


def gabor_component_response(x, fs, f0_hz, sigma_s, component="magnitude"):
    even = gabor_response_component(x, fs, f0_hz, sigma_s, "even")
    if component == "even":
        return even
    odd = gabor_response_component(x, fs, f0_hz, sigma_s, "odd")
    if component == "odd":
        return odd
    if component == "magnitude":
        return np.sqrt(even ** 2 + odd ** 2)
    raise ValueError("component deve ser 'even', 'odd' ou 'magnitude'")


def normalize_abs_response(response):
    values = np.abs(np.asarray(response, dtype=float))
    max_value = float(np.max(values)) if len(values) else 0.0
    return values / max(max_value, 1e-20)


def detect_gabor_wave_peaks(responses, ann_samples, fs, bank, n_samples):
    rows = []
    for beat_id, r_sample in enumerate(ann_samples, start=1):
        for wave, response in responses.items():
            spec = bank[wave]
            start_offset_s, end_offset_s = spec["window_s"]
            start = max(0, int(round(r_sample + start_offset_s * fs)))
            end = min(n_samples, int(round(r_sample + end_offset_s * fs)))
            if end <= start:
                continue

            local = np.abs(response[start:end]).copy()
            expected_offset_s = spec.get("expected_offset_s")
            prior_sigma_s = spec.get("prior_sigma_s")
            prior_weight = np.ones_like(local)
            if expected_offset_s is not None and prior_sigma_s is not None:
                indices = np.arange(start, end)
                offsets_s = (indices - r_sample) / fs
                prior_weight = np.exp(-0.5 * ((offsets_s - expected_offset_s) / prior_sigma_s) ** 2)
                local = local * prior_weight

            local_peak = int(np.argmax(local))
            peak = start + local_peak
            rows.append({
                "batimento": beat_id,
                "onda": wave,
                "tempo_s": float(peak / fs),
                "offset_do_r_ms": float(1000.0 * (peak - r_sample) / fs),
                "resposta_abs": float(np.abs(response[peak])),
                "peso_prior": float(prior_weight[local_peak]),
                "score": float(local[local_peak]),
            })
    return pd.DataFrame(rows)


def evaluate_gabor_parameter_grid(x, fs, ann_samples, wave_specs, f0_values, sigma_values):
    rows = []
    for wave, spec in wave_specs.items():
        qrs_window = (-0.06, 0.08)
        for f0_hz in f0_values:
            for sigma_s in sigma_values:
                response = gabor_component_response(x, fs, f0_hz, sigma_s, spec["component"])
                peak_values = []
                qrs_values = []
                offsets_ms = []
                for r_sample in ann_samples:
                    start = max(0, int(round(r_sample + spec["window_s"][0] * fs)))
                    end = min(len(x), int(round(r_sample + spec["window_s"][1] * fs)))
                    if end <= start:
                        continue

                    local = np.abs(response[start:end]).copy()
                    expected_offset_s = spec.get("expected_offset_s")
                    prior_sigma_s = spec.get("prior_sigma_s")
                    if expected_offset_s is not None and prior_sigma_s is not None:
                        indices = np.arange(start, end)
                        offsets_s = (indices - r_sample) / fs
                        prior = np.exp(-0.5 * ((offsets_s - expected_offset_s) / prior_sigma_s) ** 2)
                        local = local * prior

                    peak = start + int(np.argmax(local))
                    peak_values.append(float(np.abs(response[peak])))
                    offsets_ms.append(float(1000.0 * (peak - r_sample) / fs))

                    qrs_start = max(0, int(round(r_sample + qrs_window[0] * fs)))
                    qrs_end = min(len(x), int(round(r_sample + qrs_window[1] * fs)))
                    if qrs_end > qrs_start:
                        qrs_values.append(float(np.max(np.abs(response[qrs_start:qrs_end]))))

                rows.append({
                    "onda": wave,
                    "componente": spec["component"],
                    "f0_hz": f0_hz,
                    "sigma_s": sigma_s,
                    "media_pico_janela": float(np.mean(peak_values)) if peak_values else np.nan,
                    "razao_janela_qrs": float(np.mean(peak_values) / max(np.mean(qrs_values), 1e-20)) if qrs_values else np.nan,
                    "media_offset_ms": float(np.mean(offsets_ms)) if offsets_ms else np.nan,
                    "std_offset_ms": float(np.std(offsets_ms)) if offsets_ms else np.nan,
                })
    return pd.DataFrame(rows)


def plot_gabor_kernels(fs, configs):
    fig, axes = plt.subplots(len(configs), 1, figsize=(12, 2.4 * len(configs)), sharex=False)
    if len(configs) == 1:
        axes = [axes]
    for ax, cfg in zip(axes, configs, strict=False):
        t, h = gabor_kernel(fs, cfg["f0_hz"], cfg["sigma_s"], phase=cfg.get("phase", 0.0))
        ax.plot(t, h, color=cfg.get("color", "#1f77b4"))
        ax.set_title(f"f0 = {cfg['f0_hz']} Hz, sigma = {cfg['sigma_s']} s")
        ax.set_xlabel("Tempo relativo (s)")
        ax.set_ylabel("Amplitude")
    fig.tight_layout()
    return fig, axes


def plot_gabor_phase_components(x, t, fs, f0_hz, sigma_s, title):
    responses = {
        "par": gabor_component_response(x, fs, f0_hz, sigma_s, "even"),
        "impar": gabor_component_response(x, fs, f0_hz, sigma_s, "odd"),
        "magnitude": gabor_component_response(x, fs, f0_hz, sigma_s, "magnitude"),
    }
    fig, axes = plt.subplots(4, 1, figsize=(13, 7.5), sharex=True)
    axes[0].plot(t, x, color="#1f77b4", linewidth=1.0)
    axes[0].set_title("ECG filtrado")
    colors = {"par": "#2a9d8f", "impar": "#9467bd", "magnitude": "#e76f51"}
    for ax, (name, response) in zip(axes[1:], responses.items(), strict=False):
        ax.plot(t, normalize_abs_response(response), color=colors[name], linewidth=1.1)
        ax.set_ylabel(name)
        ax.grid(True, alpha=0.25)
    axes[-1].set_xlabel("Tempo (s)")
    fig.suptitle(title, y=1.01)
    fig.tight_layout()
    return fig, axes


def plot_gabor_detection_bank(t, x, ann_samples, fs, responses, peak_table, bank):
    fig, axes = plt.subplots(len(bank) + 1, 1, figsize=(13, 2.1 * (len(bank) + 1)), sharex=True)
    axes[0].plot(t, x, color="#1f77b4", linewidth=1.0)
    axes[0].set_title("ECG filtrado")
    for sample in ann_samples:
        axes[0].axvline(sample / fs, color="#d62728", alpha=0.40, linewidth=1.0)

    for ax, (wave, spec) in zip(axes[1:], bank.items(), strict=False):
        response_norm = normalize_abs_response(responses[wave])
        ax.plot(t, response_norm, color="#5f6c7b", linewidth=0.9, alpha=0.75)
        for sample in ann_samples:
            start_w, end_w = spec["window_s"]
            ax.axvspan(sample / fs + start_w, sample / fs + end_w, color=spec["color"], alpha=0.10)
            ax.axvline(sample / fs, color="#d62728", alpha=0.20, linewidth=0.8)

        subset = peak_table[peak_table["onda"] == wave]
        if not subset.empty:
            peak_y = np.interp(subset["tempo_s"].to_numpy(), t, response_norm)
            ax.scatter(
                subset["tempo_s"],
                peak_y,
                color=spec["color"],
                edgecolor="black",
                linewidth=0.5,
                s=34,
                zorder=4,
            )
        ax.set_title(f"{wave}: {spec['component']}, f0={spec['f0_hz']} Hz, sigma={spec['sigma_s']} s")
        ax.set_ylabel("Resp.")
        ax.grid(True, alpha=0.25)
    axes[-1].set_xlabel("Tempo (s)")
    axes[-1].set_xlim(float(t[0]), float(t[-1]))
    fig.legend(
        handles=[
            Line2D([0], [0], color="#5f6c7b", linewidth=1.0, label="resposta normalizada"),
            Line2D(
                [0],
                [0],
                marker="o",
                color="white",
                markerfacecolor="#5f6c7b",
                markeredgecolor="black",
                markersize=6,
                label="pico escolhido na janela",
            ),
            Line2D([0], [0], color="#d62728", linewidth=1.0, alpha=0.4, label="pico R anotado"),
        ],
        loc="lower center",
        ncol=3,
        bbox_to_anchor=(0.5, 0.0),
        frameon=True,
    )
    fig.tight_layout(rect=[0, 0.07, 1, 1])
    return fig, axes

"""### 1.6.8 STFT e descritores tempo-frequência

Estas funções calculam a STFT, exibem o espectrograma e resumem a distribuição de potência por centroide, largura de banda e energia por faixas.
"""

def stft_power(x, fs, window_s=0.25, overlap=0.85):
    nperseg = max(32, int(round(window_s * fs)))
    noverlap = int(round(overlap * nperseg))
    f, t, Z = signal.stft(
        x,
        fs=fs,
        window="hann",
        nperseg=nperseg,
        noverlap=noverlap,
        boundary=None,
        padded=False,
    )
    power = np.abs(Z) ** 2
    return f, t, power


def plot_stft(x, fs, title, max_freq=80.0):
    f, tt, power = stft_power(x, fs)
    mask = f <= max_freq
    fig, ax = plt.subplots(figsize=(12, 4))
    pcm = ax.pcolormesh(tt, f[mask], 10 * np.log10(power[mask] + 1e-20), shading="auto", cmap="magma")
    ax.set_title(title)
    ax.set_xlabel("Tempo (s)")
    ax.set_ylabel("Frequencia (Hz)")
    fig.colorbar(pcm, ax=ax, label="Potencia (dB)")
    fig.tight_layout()
    return fig, ax


def stft_descriptors(x, fs):
    f, _, power = stft_power(x, fs)
    freq_energy = np.sum(power, axis=1)
    weights = freq_energy / max(np.sum(freq_energy), 1e-20)
    centroid = float(np.sum(f * weights))
    bandwidth = float(np.sqrt(np.sum(((f - centroid) ** 2) * weights)))
    return {
        "energia_total_stft": float(np.sum(power)),
        "centroide_hz": centroid,
        "largura_banda_hz": bandwidth,
        "energia_0p5_4": band_power(x, fs, 0.5, 4.0),
        "energia_4_8": band_power(x, fs, 4.0, 8.0),
        "energia_8_20": band_power(x, fs, 8.0, 20.0),
        "energia_20_40": band_power(x, fs, 20.0, 40.0),
    }

"""### 1.6.9 Extração de features por batimento

Estas funções transformam cada janela de batimento em uma linha tabular com features morfológicas, rítmicas, espectrais e de Gabor.
"""

def window_slice_by_seconds(values, fs, start_s, end_s, center_index=None):
    center = len(values) // 2 if center_index is None else int(np.clip(center_index, 0, len(values) - 1))
    lo = max(0, center + int(round(start_s * fs)))
    hi = min(len(values), center + int(round(end_s * fs)))
    return values[lo:hi]


def extract_morphology_features(beat, fs, r_index=None):
    x = np.asarray(beat, dtype=float)
    center = len(x) // 2 if r_index is None else int(np.clip(r_index, 0, len(x) - 1))
    diff = np.diff(x)
    return {
        "r_amp": float(x[center]),
        "beat_peak_to_peak": float(np.ptp(x)),
        "beat_energy": float(np.sum(x ** 2)),
        "beat_abs_area": float(np.sum(np.abs(x)) / fs),
        "beat_std": float(np.std(x)),
        "max_abs_slope": float(np.max(np.abs(diff)) * fs) if diff.size else 0.0,
    }


def extract_rr_features(rr_prev, rr_next):
    ratio = np.nan if not np.isfinite(rr_prev) or not np.isfinite(rr_next) or rr_next == 0 else rr_prev / rr_next
    return {"rr_prev_s": rr_prev, "rr_next_s": rr_next, "rr_ratio": ratio}


def extract_spectral_features(beat, fs):
    freqs, pxx = signal.welch(beat, fs=fs, nperseg=min(len(beat), 256))
    weights = pxx / max(np.sum(pxx), 1e-20)
    centroid = float(np.sum(freqs * weights))
    bandwidth = float(np.sqrt(np.sum(((freqs - centroid) ** 2) * weights)))
    return {
        "spectral_centroid_hz": centroid,
        "spectral_bandwidth_hz": bandwidth,
        "band_power_8_20": band_power(beat, fs, 8.0, 20.0),
        "band_power_20_40": band_power(beat, fs, 20.0, 40.0),
    }


def extract_gabor_features(beat, fs, r_index=None):
    features = {}
    configs = {
        "p": {"f0_hz": 8.0, "sigma_s": 0.110, "component": "even", "window": (-0.28, -0.07)},
        "qrs": {"f0_hz": 15.0, "sigma_s": 0.020, "component": "magnitude", "window": (-0.07, 0.07)},
        "t": {"f0_hz": 6.0, "sigma_s": 0.110, "component": "even", "window": (0.18, 0.45)},
    }
    for name, cfg in configs.items():
        start_s, end_s = cfg["window"]
        response = gabor_component_response(beat, fs, cfg["f0_hz"], cfg["sigma_s"], cfg["component"])
        segment = window_slice_by_seconds(response, fs, start_s, end_s, center_index=r_index)
        features[f"{name}_gabor_energy"] = float(np.sum(segment ** 2)) if len(segment) else 0.0
        features[f"{name}_gabor_max"] = float(np.max(np.abs(segment))) if len(segment) else 0.0
    return features


def extract_all_features(raw_beat, filtered_beat, fs, rr_prev, rr_next, r_index=None):
    features = {}
    features.update({f"raw_{k}": v for k, v in extract_morphology_features(raw_beat, fs, r_index=r_index).items()})
    features.update({f"filt_{k}": v for k, v in extract_morphology_features(filtered_beat, fs, r_index=r_index).items()})
    features.update(extract_rr_features(rr_prev, rr_next))
    features.update(extract_spectral_features(filtered_beat, fs))
    features.update(extract_gabor_features(filtered_beat, fs, r_index=r_index))
    return features

"""### 1.6.10 Construção do dataset e modelagem

Estas funções montam a tabela por batimento e calculam as métricas dos modelos. O split é feito por registro, não por batimento, para reduzir vazamento entre treino e teste.
"""

def filter_full_record(x, fs):
    filters = make_hamming_filters(fs)
    stages = apply_filter_stages(x, filters)
    return stages["passa_baixa_40"]


def build_beat_dataset(record_names, split_name, max_beats_per_record=350):
    rows = []
    for record_name in record_names:
        raw, fs_rec, channel, ann_samples, ann_symbols = load_record(record_name)
        filtered = filter_full_record(raw, fs_rec)
        valid_mask = valid_beat_mask(ann_symbols)
        valid_samples = ann_samples[valid_mask]
        valid_symbols = ann_symbols[valid_mask]
        kept = 0
        for idx, (sample, symbol) in enumerate(zip(valid_samples, valid_symbols, strict=False)):
            bounds = full_beat_bounds(sample, fs_rec, len(raw), pre_s=0.25, post_s=0.45)
            if bounds is None:
                continue
            start, end = bounds
            rr_prev, rr_next = rr_context(valid_samples, idx, fs_rec)
            raw_beat = raw[start:end]
            filtered_beat = filtered[start:end]
            r_index = int(sample) - start
            rows.append({
                "record": record_name,
                "split": split_name,
                "sample": int(sample),
                "ann_symbol": str(symbol),
                "label_binary": binary_label(str(symbol)),
                "fs_hz": fs_rec,
                **extract_all_features(raw_beat, filtered_beat, fs_rec, rr_prev, rr_next, r_index=r_index),
            })
            kept += 1
            if max_beats_per_record is not None and kept >= max_beats_per_record:
                break
        print(record_name, split_name, "batimentos usados:", kept)
    return pd.DataFrame(rows)


def evaluate_model(name, y_true, y_pred, score):
    metrics = {
        "modelo": name,
        "accuracy": accuracy_score(y_true, y_pred),
        "precision": precision_score(y_true, y_pred, zero_division=0),
        "recall": recall_score(y_true, y_pred, zero_division=0),
        "f1": f1_score(y_true, y_pred, zero_division=0),
        "pr_auc": average_precision_score(y_true, score),
        "roc_auc": roc_auc_score(y_true, score) if len(np.unique(y_true)) == 2 else np.nan,
    }
    cm = confusion_matrix(y_true, y_pred, labels=[0, 1])
    metrics.update({"tn": cm[0, 0], "fp": cm[0, 1], "fn": cm[1, 0], "tp": cm[1, 1]})
    return metrics


def plot_curves(y_true, model_scores):
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    for name, score in model_scores.items():
        precision, recall, _ = precision_recall_curve(y_true, score)
        fpr, tpr, _ = roc_curve(y_true, score)
        axes[0].plot(recall, precision, label=name)
        axes[1].plot(fpr, tpr, label=name)
    axes[0].set_title("Curva Precision-Recall")
    axes[0].set_xlabel("Recall")
    axes[0].set_ylabel("Precision")
    axes[1].set_title("Curva ROC")
    axes[1].set_xlabel("FPR")
    axes[1].set_ylabel("TPR")
    for ax in axes:
        ax.legend()
        ax.grid(True, alpha=0.3)
    fig.tight_layout()
    return fig, axes

"""# 2. ECG e base de dados

O eletrocardiograma é um sinal biomédico unidimensional que representa a atividade elétrica cardíaca ao longo do tempo. Cada batimento normalmente inclui uma onda P, associada à despolarização atrial, um complexo QRS, associado à despolarização ventricular, e uma onda T, associada à repolarização ventricular.

![Anatomia do ECG](https://ecgwaves.com/wp-content/uploads/2018/01/ekg-ecg-interpretation-p-qrs-st-t-wave.jpg)

## 2.1 MIT-BIH Arrhythmia Database

A base MIT-BIH contém registros de ECG anotados, amostrados a 360 Hz, com dois canais por registro. Sempre que disponível, o canal MLII será usado por ser uma derivação comum em análises de batimentos. A unidade de análise final será o batimento segmentado em torno da anotação WFDB.
"""

RECORD_REF = "100"
x_full, fs, channel_name, ann_samples_all, ann_symbols_all = load_record(RECORD_REF)

mask_valid = valid_beat_mask(ann_symbols_all)
beat_samples = ann_samples_all[mask_valid]
beat_symbols = ann_symbols_all[mask_valid]

start_short, end_short, chosen_beats = make_sample_window_from_beats(
    beat_samples, fs, start_beat_idx=1, n_beats=4, margin_s=0.25
)
x_raw_short = x_full[start_short:end_short]
t_short = np.arange(len(x_raw_short)) / fs

local_ann_mask = (ann_samples_all >= start_short) & (ann_samples_all < end_short)
ann_local = ann_samples_all[local_ann_mask] - start_short
sym_local = ann_symbols_all[local_ann_mask]

print(f"Registro {RECORD_REF}, canal {channel_name}, fs = {fs:.0f} Hz")
print(f"Janela curta com {len(chosen_beats)} batimentos validos e {len(x_raw_short)} amostras")
plot_ecg_window(t_short, x_raw_short, ann_local, sym_local, "ECG bruto em janela curta")
plt.show()

"""# 3. Análise prévia do ruído e das bandas de interesse

A filtragem será escolhida depois de medir o que aparece no sinal bruto. A deriva de linha de base costuma ocupar frequências abaixo de 0,5 Hz. O conteúdo diagnóstico principal do ECG aparece em frequências baixas e intermediárias, enquanto o complexo QRS concentra parte importante da energia entre aproximadamente 8 Hz e 20 Hz. A interferência de rede, quando presente, aparece perto de 60 Hz.
"""

raw_band_table = psd_table(x_raw_short, fs)
display(raw_band_table)
plot_psd(x_raw_short, fs, "PSD do ECG bruto na janela curta")
plt.show()

print("Media da janela bruta:", float(np.mean(x_raw_short)))
print("Desvio-padrao da janela bruta:", float(np.std(x_raw_short)))

"""# 4. Pré-processamento e filtragem FIR

A cascata FIR será formada por passa-alta e passa-baixa. A escolha por FIR de fase linear facilita preservar a morfologia temporal do ECG. A aplicação com `filtfilt` remove o atraso de grupo, o que é importante porque o pico R serve como referência de segmentação dos batimentos. O rejeita-faixa em 59-61 Hz não entra na cascata principal porque o passa-baixa em 40 Hz já remove a região da interferência de rede.

## 4.1 Implementando FIR's e IIR
"""

filters_hamming = make_hamming_filters(fs)
filters_remez = make_remez_filters(fs)
filters_iir = make_butter_iir_filters(fs, order=4)

filter_info = pd.DataFrame([
    {"metodo": method_name, "filtro": filter_name, "coeficientes": len(h), "ordem": len(h) - 1}
    for method_name, filters in {
        "Hamming": filters_hamming,
        "Parks-McClellan": filters_remez,
    }.items()
    for filter_name, h in filters.items()
])

iir_info = pd.DataFrame([
    {
        "metodo": "Butterworth IIR",
        "filtro": filter_name,
        "secoes_sos": sos.shape[0],
        "ordem_aproximada": 2 * sos.shape[0],
    }
    for filter_name, sos in filters_iir.items()
])

"""## 4.2 Visualizando Resposta em Frequência"""

display(filter_info)

plot_filter_response(filters_hamming, fs, "Resposta em frequencia dos filtros FIR (Hamming)")
plt.show()

plot_filter_response(filters_remez, fs, "Resposta em frequencia dos filtros FIR (Parks-McClellan)")
plt.show()

display(iir_info)

plot_iir_response(filters_iir, fs, "Resposta em frequencia dos filtros IIR (Butterworth)")
plt.show()

"""## 4.3 Visualizando Aplicação em Cascata

A ordem dos filtros vem da largura de transição. Na janela de Hamming, a aproximação `N = 3,3 fs / delta_f` aumenta o número de coeficientes quando a transição precisa ser estreita. Por isso, o passa-alta em 0,5 Hz exige mais coeficientes que o passa-baixa em 40 Hz. O rejeita-faixa de 60 Hz não é aplicado porque seria redundante depois da decisão de limitar a banda preservada a 40 Hz.
"""

# A cascata e aplicada no registro completo, porque filtros FIR longos precisam
# de contexto temporal suficiente para o filtfilt.
stages_full = apply_filter_stages(x_full, filters_hamming)
stages_short = {name: values[start_short:end_short] for name, values in stages_full.items()}
x_filtered_short = stages_short["passa_baixa_40"]
zoom_xlim = beat_zoom_xlim(t_short, ann_local, fs, n_beats=2)

fig, axes = plt.subplots(len(stages_short), 1, figsize=(13, 9), sharex=True)
for ax, (name, y) in zip(axes, stages_short.items(), strict=False):
    ax.plot(t_short, x_raw_short, color="#4a4a4a", alpha=0.80, linewidth=1.0, label="bruto")
    ax.plot(t_short, y, color="#1f77b4", linewidth=1.2, label=name)
    for sample in ann_local:
        ax.axvline(t_short[sample], color="#d62728", alpha=0.45, linewidth=1.1)
    ax.set_xlim(*zoom_xlim)
    ax.set_ylabel("mV")
    ax.set_title(f"Estagio: {name}", loc="left", fontsize=10)
axes[-1].set_xlabel("Tempo (s)")
fig.suptitle("Aplicacao progressiva da cascata FIR", y=1.01)
fig.legend(
    handles=[
        Line2D([0], [0], color="#4a4a4a", linewidth=1.0, label="bruto"),
        Line2D([0], [0], color="#1f77b4", linewidth=1.2, label="saida do estagio"),
        Line2D([0], [0], color="#d62728", linewidth=1.1, label="pico R anotado"),
    ],
    loc="upper center",
    ncol=3,
    bbox_to_anchor=(0.5, 1.0),
)
fig.tight_layout(rect=[0, 0, 1, 0.95])
plt.show()

"""## 4.4 Visualizando FIR's x IIR no tempo"""

stages_hamming_full, timing_hamming = time_stage_application(
    "FIR Hamming",
    lambda: apply_filter_stages(x_full, filters_hamming),
)
stages_remez_full, timing_remez = time_stage_application(
    "FIR Parks-McClellan",
    lambda: apply_filter_stages(x_full, filters_remez),
)
stages_iir_full, timing_iir = time_stage_application(
    "IIR Butterworth",
    lambda: apply_iir_stages(x_full, filters_iir),
)

timing_table = pd.DataFrame([timing_hamming, timing_remez, timing_iir])
display(timing_table)

x_hamming_short = stages_hamming_full["passa_baixa_40"][start_short:end_short]
x_remez_short = stages_remez_full["passa_baixa_40"][start_short:end_short]
x_iir_short = stages_iir_full["passa_baixa_40"][start_short:end_short]

fig, ax = plt.subplots(figsize=(13, 4.5))
ax.plot(t_short, x_raw_short, color="#4a4a4a", alpha=0.55, linewidth=1.0, label="bruto")
ax.plot(t_short, x_hamming_short, color="#1f77b4", linewidth=1.25, label="Hamming")
ax.plot(t_short, x_remez_short, color="#e76f51", linewidth=1.1, label="Parks-McClellan")
ax.plot(t_short, x_iir_short, color="#2a9d8f", linewidth=1.1, label="Butterworth IIR")
for sample in ann_local:
    ax.axvline(t_short[sample], color="#d62728", alpha=0.45, linewidth=1.1)
ax.set_xlim(*zoom_xlim)
ax.set_title("Comparacao do sinal filtrado por Hamming, Parks-McClellan e IIR")
ax.set_xlabel("Tempo (s)")
ax.set_ylabel("mV")
ax.legend(loc="lower center", bbox_to_anchor=(0.5, -0.38), ncol=4, frameon=True)
fig.tight_layout(rect=[0, 0.08, 1, 1])
plt.show()

x_filtered_short = x_hamming_short

"""# 5. Verificação experimental da convolução

A filtragem FIR é uma convolução discreta entre o sinal e a resposta ao impulso. Para evidenciar a operação matemática, a convolução temporal será implementada com laços explícitos. Depois, a mesma operação será feita por FFT com zero-padding. Sem zero-padding, a FFT calcula convolução circular, o que altera a borda e pode contaminar a comparação.
"""

h_demo = filters_hamming["passa_baixa_40"]

y_time = linear_convolution_same_manual(x_raw_short, h_demo)
y_fft = fft_convolution_same_linear(x_raw_short, h_demo)
y_circular = fft_convolution_circular_wrong(x_raw_short, h_demo)

comparison = pd.DataFrame([
    {"comparacao": "tempo manual vs FFT com padding", "MSE": mse(y_time, y_fft)},
    {"comparacao": "tempo manual vs FFT circular sem padding", "MSE": mse(y_time, y_circular)},
])
display(comparison)

fig, ax = plt.subplots(figsize=(13, 4))
ax.plot(t_short, x_raw_short, color="#4a4a4a", alpha=0.45, linewidth=1.0, label="bruto")
ax.plot(t_short, y_time, color="#1f77b4", label="convolucao temporal manual", linewidth=1.25)
ax.plot(t_short, y_fft, color="#e76f51", linestyle="--", label="FFT com zero-padding", linewidth=1.1)
ax.plot(t_short, y_circular, color="#2ca02c", linestyle=":", label="FFT circular sem padding", linewidth=1.9)
ax.set_xlim(*zoom_xlim)
ax.set_title("Convolucao temporal, FFT linear e FFT circular")
ax.set_xlabel("Tempo (s)")
ax.set_ylabel("Amplitude")
ax.legend(loc="lower center", bbox_to_anchor=(0.5, -0.38), ncol=4, frameon=True)
fig.tight_layout(rect=[0, 0.01, 1, 1])
plt.show()

"""**Interpretação:** O MSE entre convolução manual e FFT com zero-padding deve ficar próximo de zero, limitado por erro numérico. O MSE da FFT circular deve ser maior, principalmente por causa da mistura artificial entre final e início do sinal.

# 6. Avaliação da filtragem

A filtragem não deve ser julgada apenas por parecer visualmente mais limpa. A avaliação combina atenuação por bandas, estimativa de SNR, preservação da banda passante e erro percentual do pico R. Como não existe sinal limpo de referência, a estimativa de ruído será aproximada pela energia fora da faixa diagnóstica e pela diferença entre sinal bruto e filtrado.
"""

band_summary, snr_summary = denoising_summary(x_raw_short, x_filtered_short, fs)
r_summary = r_peak_error_table(x_raw_short, x_filtered_short, ann_local, fs)

display(band_summary)
display(snr_summary)
display(r_summary)

plot_psd(x_raw_short, fs, "PSD do ECG bruto", max_freq=100)
plt.show()
plot_psd(x_filtered_short, fs, "PSD do ECG filtrado", max_freq=100)
plt.show()

"""# 7. Filtros de Gabor 1D

## 7.1 Visualizando o efeito de f0 e de sigma

O filtro de Gabor 1D combina uma senoide com uma envoltória Gaussiana. A frequência central `f0` seleciona uma escala espectral, enquanto `sigma` controla a largura temporal. Valores menores de `sigma` localizam melhor eventos curtos, mas espalham mais a resposta em frequência. Valores maiores melhoram a seletividade espectral, mas borram a localização temporal.

No ECG, esse compromisso é útil porque o QRS é curto e mais rico em frequências intermediárias, enquanto P e T tendem a ser mais suaves e mais largas.
"""

kernel_configs = [
    {"f0_hz": 15.0, "sigma_s": 0.10, "color": "#457b9d"},
    {"f0_hz": 15.0, "sigma_s": 0.05, "color": "#2a9d8f"},
    {"f0_hz": 15.0, "sigma_s": 0.02, "color": "#e76f51"},
]
plot_gabor_kernels(fs, kernel_configs)
plt.show()

kernel_configs = [
    {"f0_hz": 5.0, "sigma_s": 0.05, "color": "#457b9d"},
    {"f0_hz": 10.0, "sigma_s": 0.05, "color": "#2a9d8f"},
    {"f0_hz": 15.0, "sigma_s": 0.05, "color": "#e76f51"},
]
plot_gabor_kernels(fs, kernel_configs)
plt.show()

"""## 7.2 Visualizando o efeito de par, ímpar e magnitude"""

zoom_start, zoom_end = beat_zoom_xlim(t_short, ann_local, fs, n_beats=2)

fig, axes = plot_gabor_phase_components(
    x_filtered_short,
    t_short,
    fs,
    f0_hz=18.0,
    sigma_s=0.020,
    title="Influencia dos componentes par, impar e magnitude no Gabor para QRS",
)
for ax in axes:
    ax.set_xlim(zoom_start, zoom_end)
plt.show()

"""## 7.3 Implementando Parametros de Busca e Banco de Gabor"""

GABOR_SEARCH_SPECS = {
    "P": {
        "component": "even",
        "window_s": (-0.28, -0.07),
        "expected_offset_s": -0.16,
        "prior_sigma_s": 0.055,
    },
    "QRS": {
        "component": "magnitude",
        "window_s": (-0.07, 0.07),
        "expected_offset_s": 0.0,
        "prior_sigma_s": 0.025,
    },
    "T": {
        "component": "even",
        "window_s": (0.18, 0.45),
        "expected_offset_s": 0.30,
        "prior_sigma_s": 0.080,
    },
}

gabor_grid_df = evaluate_gabor_parameter_grid(
    x_filtered_short,
    fs,
    ann_local,
    GABOR_SEARCH_SPECS,
    f0_values=[4, 6, 8, 12, 15, 18, 22],
    sigma_values=[0.020, 0.035, 0.055, 0.080, 0.110],
)

GABOR_BANK = {
    "P": {
        "f0_hz": 8.0,
        "sigma_s": 0.110,
        "component": "even",
        "window_s": (-0.28, -0.07),
        "expected_offset_s": -0.13,
        "prior_sigma_s": 0.060,
        "color": "#2a9d8f",
    },
    "QRS": {
        "f0_hz": 15.0,
        "sigma_s": 0.020,
        "component": "magnitude",
        "window_s": (-0.07, 0.07),
        "expected_offset_s": 0.0,
        "prior_sigma_s": 0.025,
        "color": "#e76f51",
    },
    "T": {
        "f0_hz": 6.0,
        "sigma_s": 0.110,
        "component": "even",
        "window_s": (0.18, 0.45),
        "expected_offset_s": 0.25,
        "prior_sigma_s": 0.090,
        "color": "#457b9d",
    },
}

gabor_responses = {
    wave: gabor_component_response(
        x_filtered_short,
        fs,
        spec["f0_hz"],
        spec["sigma_s"],
        spec["component"],
    )
    for wave, spec in GABOR_BANK.items()
}

gabor_peak_table = detect_gabor_wave_peaks(
    gabor_responses,
    ann_local,
    fs,
    GABOR_BANK,
    len(x_filtered_short),
)

"""## 7.4 Visualizando parametros de Busca e Banco de Gabor"""

display(
    gabor_grid_df.assign(pico_negativo=-gabor_grid_df["media_pico_janela"])
    .sort_values(["onda", "std_offset_ms", "pico_negativo"])
    .groupby("onda")
    .head(6)
    .drop(columns="pico_negativo")
    .reset_index(drop=True)
)

display(gabor_peak_table)

fig, axes = plot_gabor_detection_bank(
    t_short,
    x_filtered_short,
    ann_local,
    fs,
    gabor_responses,
    gabor_peak_table,
    GABOR_BANK,
)
fig.suptitle("Banco de Gabor com janelas fisiologicas e picos candidatos", y=1.01)
plt.show()

"""# 8. Análise tempo-frequência por STFT

O espectrograma por STFT representa a potência em função do tempo e da frequência. Ele não deve ser tratado apenas como imagem. A leitura deve indicar onde a energia se concentra, como o QRS aparece no plano tempo-frequência e como a filtragem altera o espalhamento espectral.
"""

plot_stft(x_raw_short, fs, "STFT do ECG bruto")
plt.show()
plot_stft(x_filtered_short, fs, "STFT do ECG filtrado")
plt.show()

stft_table = pd.DataFrame([
    {"sinal": "bruto", **stft_descriptors(x_raw_short, fs)},
    {"sinal": "filtrado", **stft_descriptors(x_filtered_short, fs)},
])
display(stft_table)

"""# 9. Dataset por batimento

## 9.1 Implementando separação treino-teste
"""

print("Registros de treino:", TRAIN_RECORDS)
print("Registros de teste:", TEST_RECORDS)

df_train = build_beat_dataset(TRAIN_RECORDS, "train")
df_test = build_beat_dataset(TEST_RECORDS, "test")
df_beats = pd.concat([df_train, df_test], ignore_index=True)

"""O split é por registro, não por batimento. Isso evita que batimentos do mesmo paciente apareçam ao mesmo tempo no treino e no teste. A tabela por símbolo deve ser lida antes da modelagem para confirmar se o treino e o teste contêm batimentos normais e anômalos. A tabela descritiva das features de Gabor confirma que o banco decidido no capítulo 7 foi propagado para a base final.

## 9.2 Visualizando dataset final e distribuições
"""

display(df_beats.head())
display(pd.crosstab(df_beats["split"], df_beats["label_binary"]))
display(pd.crosstab(df_beats["record"], df_beats["ann_symbol"]))

GABOR_FEATURE_COLS = [
    "p_gabor_energy",
    "p_gabor_max",
    "qrs_gabor_energy",
    "qrs_gabor_max",
    "t_gabor_energy",
    "t_gabor_max",
]
display(df_beats[GABOR_FEATURE_COLS].describe().T)

"""# 10. Classificação normal versus anômalo

A SVM supervisionada recebe exemplos normais e anômalos no treinamento e funciona como baseline didático. A One-Class SVM recebe apenas batimentos normais no treinamento e aprende uma região de normalidade. Essa diferença precisa ficar explícita, porque a segunda formulação é mais próxima de detecção de anomalias.

A comparação é entre SVM supervisionada e One-Class SVM.

O conjunto de atributos combina morfologia, intervalos RR, descritores espectrais e as seis features de Gabor escolhidas após a análise do banco. A etapa de classificação não escolhe novos parâmetros de Gabor; ela apenas testa se os descritores definidos antes ajudam a separar batimentos normais de anômalos.
"""

METADATA_COLS = {"record", "split", "sample", "ann_symbol", "label_binary", "fs_hz"}
FEATURE_COLS = [
    col for col in df_beats.columns
    if col not in METADATA_COLS and pd.api.types.is_numeric_dtype(df_beats[col])
]

feature_groups = pd.DataFrame({
    "feature": FEATURE_COLS,
    "grupo": [
        "gabor" if "gabor" in col else
        "rr" if col.startswith("rr_") else
        "espectral" if col.startswith("spectral_") or col.startswith("band_power_") else
        "morfologia"
        for col in FEATURE_COLS
    ],
})
display(feature_groups)

train_df = df_beats[df_beats["split"] == "train"].copy()
test_df = df_beats[df_beats["split"] == "test"].copy()

X_train_raw = train_df[FEATURE_COLS].replace([np.inf, -np.inf], np.nan)
fill_values = X_train_raw.median(numeric_only=True).fillna(0.0)
X_train = X_train_raw.fillna(fill_values)
X_test = test_df[FEATURE_COLS].replace([np.inf, -np.inf], np.nan).fillna(fill_values)

y_train = train_df["label_binary"].astype(int).to_numpy()
y_test = test_df["label_binary"].astype(int).to_numpy()

print("Features usadas:", len(FEATURE_COLS))
print("Treino:", X_train.shape, "Teste:", X_test.shape)
print("Normais no treino:", int(np.sum(y_train == 0)), "Anomalos no treino:", int(np.sum(y_train == 1)))
print("Features de Gabor:", [col for col in FEATURE_COLS if "gabor" in col])

svm_sup = Pipeline([
    ("scale", StandardScaler()),
    ("model", SVC(kernel="rbf", class_weight="balanced", probability=True, random_state=RANDOM_STATE)),
])
svm_sup.fit(X_train, y_train)
svm_sup_score = svm_sup.predict_proba(X_test)[:, 1]
svm_sup_pred = svm_sup.predict(X_test)

normal_train_mask = y_train == 0
one_class_nu = 0.05
oc_svm = Pipeline([
    ("scale", StandardScaler()),
    ("model", OneClassSVM(kernel="rbf", nu=one_class_nu, gamma="scale")),
])
oc_svm.fit(X_train.loc[normal_train_mask])
oc_score = -oc_svm.decision_function(X_test)
oc_pred = np.where(oc_svm.predict(X_test) == -1, 1, 0)

print("nu usado na One-Class SVM:", one_class_nu)
print("Batimentos usados no treino one-class:", int(np.sum(normal_train_mask)))

results = pd.DataFrame([
    evaluate_model("SVM supervisionada", y_test, svm_sup_pred, svm_sup_score),
    evaluate_model("One-Class SVM", y_test, oc_pred, oc_score),
])
display(results)

plot_curves(y_test, {
    "SVM supervisionada": svm_sup_score,
    "One-Class SVM": oc_score,
})
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(10, 4))
for ax, name, pred in [
    (axes[0], "SVM supervisionada", svm_sup_pred),
    (axes[1], "One-Class SVM", oc_pred),
]:
    cm = confusion_matrix(y_test, pred, labels=[0, 1])
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", cbar=False, ax=ax)
    ax.set_title(name)
    ax.set_xlabel("Predito")
    ax.set_ylabel("Real")
    ax.set_xticklabels(["normal", "anomalo"])
    ax.set_yticklabels(["normal", "anomalo"])
fig.tight_layout()
plt.show()

"""**Interpretação:** A acurácia deve ser lida com cuidado porque a classe normal costuma ser majoritária. PR-AUC, precision, recall, F1 e matriz de confusão mostram melhor o compromisso entre encontrar anomalias e evitar falsos alarmes. A SVM supervisionada pode ter vantagem por usar anomalias no treino. A One-Class SVM deve ser avaliada como detector de novidade treinado apenas com normais.

Os resultados desta seção avaliam o conjunto de features definido antes da modelagem. Se a One-Class SVM tiver desempenho baixo, isso não significa automaticamente que Gabor não funciona; significa que esta combinação específica de morfologia, RR, espectro e seis features de Gabor precisa ser interpretada contra as métricas obtidas.

# 11. Síntese dos resultados
"""

final_summary = {
    "mse_convolucao_tempo_fft": mse(y_time, y_fft),
    "mse_convolucao_tempo_fft_circular": mse(y_time, y_circular),
    "snr_bandas_bruto_db": snr_band_estimate_db(x_raw_short, fs),
    "snr_bandas_filtrado_db": snr_band_estimate_db(x_filtered_short, fs),
    "erro_R_percentual_medio": float(r_summary["erro_R_percentual"].mean()) if len(r_summary) else np.nan,
    "deslocamento_R_abs_medio_ms": float(r_summary["deslocamento_ms"].abs().mean()) if len(r_summary) else np.nan,
}
display(pd.DataFrame([final_summary]))
display(results)

"""# 12. Referências de apoio para a apresentação

Esta célula reúne referências curtas para justificar as escolhas principais do notebook. A ideia não é reproduzir toda a bibliografia do artigo, mas deixar claro de onde vêm as bases metodológicas caso alguma decisão seja questionada na apresentação.

## Base de dados e anotações

- Moody, G. B.; Mark, R. G. **The impact of the MIT-BIH Arrhythmia Database**. *IEEE Engineering in Medicine and Biology Magazine*, 2001. DOI: [10.1109/51.932724](https://doi.org/10.1109/51.932724).  
  (Sustenta o uso da MIT-BIH como base clássica de ECG anotado para avaliação de algoritmos de arritmia.)

- Goldberger, A. L. et al. **PhysioBank, PhysioToolkit, and PhysioNet: Components of a new research resource for complex physiologic signals**. *Circulation*, 2000. DOI: [10.1161/01.CIR.101.23.e215](https://doi.org/10.1161/01.CIR.101.23.e215).  
  (Sustenta a infraestrutura PhysioNet e o acesso reprodutível aos registros fisiológicos.)

- PhysioNet. **MIT-BIH Arrhythmia Database v1.0.0**. Disponível em [physionet.org/content/mitdb/1.0.0](https://physionet.org/content/mitdb/1.0.0/).  
  (Confirma que os registros têm dois canais, amostragem de 360 Hz e anotações de batimentos. A janela de segmentação não vem pronta da base.)

## Segmentação por batimento

- Qin, Q.; Li, J.; Zhang, L.; Yue, Y.; Liu, C. **Combining Low-dimensional Wavelet Features and Support Vector Machine for Arrhythmia Beat Classification**. *Scientific Reports*, 2017. DOI: [10.1038/s41598-017-06596-z](https://doi.org/10.1038/s41598-017-06596-z).  
  (Segmenta o ECG em episódios de 0,7 s baseados nas posições dos R-peaks da MIT-BIH. Também justifica a segmentação por batimento como etapa anterior à extração de features.)

- Desiani, A.; Erwin; Maiyanti, S. I.; Suprihatin, B.; Rachmatullah, N.; Fauza, A. N.; Ramayanti, I. **R-Peak Detection of Beat Segmentation and Convolution Neural Network for Arrhythmia Classification**. *Journal of Engineering Science and Technology*, 17(2), 1231-1246, 2022. Disponível em [JESTEC](https://jestec.taylors.edu.my/Vol%2017%20Issue%202%20April%20%202022/17_2_30.pdf).  
  (Explicita a mesma janela operacional usada no notebook: 0,25 s antes do R-peak e 0,45 s depois, totalizando 0,7 s ou 252 amostras em 360 Hz.)

## Filtragem, QRS e espectro

- Pan, J.; Tompkins, W. J. **A Real-Time QRS Detection Algorithm**. *IEEE Transactions on Biomedical Engineering*, 1985. DOI: [10.1109/TBME.1985.325532](https://doi.org/10.1109/TBME.1985.325532).  
  (Base clássica para tratar o QRS como evento de alta energia e transição rápida. Ajuda a justificar preservar morfologia e alinhamento do pico R.)

- Thakor, N. V.; Webster, J. G.; Tompkins, W. J. **Estimation of QRS Complex Power Spectra for Design of a QRS Filter**. *IEEE Transactions on Biomedical Engineering*, 1984. DOI: [10.1109/TBME.1984.325393](https://doi.org/10.1109/TBME.1984.325393).  
  (Sustenta a leitura espectral do QRS e a importância de frequências intermediárias, próximas da região usada nas features `8-20 Hz` e no Gabor do QRS.)

- Elgendi, M.; Mohamed, A.; Ward, R. **Efficient ECG Compression and QRS Detection for E-Health Applications**. *Scientific Reports*, 2017. DOI: [10.1038/s41598-017-00540-x](https://doi.org/10.1038/s41598-017-00540-x).  
  (Apoia o uso de faixas compatíveis com ECG e QRS em processamento eficiente. Ajuda a defender a cadeia passa-alta/passa-baixa do notebook.)

## Tempo-frequência, Gabor e STFT

- Gabor, D. **Theory of Communication**. *Journal of the Institution of Electrical Engineers*, 1946.  
  (Base conceitual da análise localizada tempo-frequência. Justifica o filtro de Gabor como senoide modulada por Gaussiana.)

- Lee, G. G.; Hu, J.-Y.; Chen, C.-F.; Lin, H.-H. **Gabor Feature Extraction for Electrocardiogram Signals**. *IEEE Biomedical Circuits and Systems Conference*, 2012. DOI: [10.1109/BioCAS.2012.6418436](https://doi.org/10.1109/BioCAS.2012.6418436).  
  (Mostra uso de Gabor como extração de features em ECG. No notebook, usamos Gabor como descritor local em janelas aproximadas de P, QRS e T.)

- Welch, P. **The use of fast Fourier transform for the estimation of power spectra**. *IEEE Transactions on Audio and Electroacoustics*, 1967. DOI: [10.1109/TAU.1967.1161901](https://doi.org/10.1109/TAU.1967.1161901).  
  (Base para a estimativa de PSD usada nas tabelas de potência por banda.)

## Features, modelos e métricas

- de Chazal, P.; O'Dwyer, M.; Reilly, R. B. **Automatic Classification of Heartbeats Using ECG Morphology and Heartbeat Interval Features**. *IEEE Transactions on Biomedical Engineering*, 2004. DOI: [10.1109/TBME.2004.827359](https://doi.org/10.1109/TBME.2004.827359).  
  (Sustenta a escolha de features morfológicas e de intervalo RR como base interpretável para classificação de batimentos.)

- Schölkopf, B. et al. **Estimating the Support of a High-Dimensional Distribution**. *Neural Computation*, 2001. DOI: [10.1162/089976601750264965](https://doi.org/10.1162/089976601750264965).  
  (Base teórica da One-Class SVM, usada no notebook como detector treinado apenas com batimentos normais.)

- Davis, J.; Goadrich, M. **The Relationship Between Precision-Recall and ROC Curves**. *ICML*, 2006. DOI: [10.1145/1143844.1143874](https://doi.org/10.1145/1143844.1143874).  
  (Ajuda a justificar por que PR-AUC, precision, recall e F1 são mais informativos que acurácia isolada em classe anômala minoritária.)
"""
